export default {
  START_USER_LOADING: "START_USER_LOADING",
  LOAD_USER: "LOAD_USER",
  LOAD_USERS: "LOAD_USERS",
  LOAD_ROOMS: "LOAD_ROOMS",
  CLEAR_READ_MESSAGES: "CLEAR_READ_MESSAGES",
  PUSH_NOTIFICATION: "PUSH_NOTIFICATION"
};
